apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
data:
  {{- range $key, $val := .Values.configmap }}
  {{ $key }}: {{ tpl ($val | toString) $ | quote}}
  {{- end }}
